# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: media.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'media.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmedia.proto\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"#\n\rSpeechRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"\x1c\n\x0cTextResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"$\n\x0eSpeechResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\",\n\x07\x45motion\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\"+\n\rEmotionsArray\x12\x1a\n\x08\x65motions\x18\x01 \x03(\x0b\x32\x08.Emotion2\xc9\x01\n\x0cMediaService\x12-\n\x0cTextToSpeech\x12\x0c.TextRequest\x1a\x0f.SpeechResponse\x12-\n\x0cSpeechToText\x12\x0e.SpeechRequest\x1a\r.TextResponse\x12\x35\n\x14\x46ilteredTextToSpeech\x12\x0c.TextRequest\x1a\x0f.SpeechResponse\x12$\n\x03\x46\x45R\x12\r.ImageRequest\x1a\x0e.EmotionsArrayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'media_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=15
  _globals['_TEXTREQUEST']._serialized_end=42
  _globals['_SPEECHREQUEST']._serialized_start=44
  _globals['_SPEECHREQUEST']._serialized_end=79
  _globals['_IMAGEREQUEST']._serialized_start=81
  _globals['_IMAGEREQUEST']._serialized_end=115
  _globals['_TEXTRESPONSE']._serialized_start=117
  _globals['_TEXTRESPONSE']._serialized_end=145
  _globals['_SPEECHRESPONSE']._serialized_start=147
  _globals['_SPEECHRESPONSE']._serialized_end=183
  _globals['_EMOTION']._serialized_start=185
  _globals['_EMOTION']._serialized_end=229
  _globals['_EMOTIONSARRAY']._serialized_start=231
  _globals['_EMOTIONSARRAY']._serialized_end=274
  _globals['_MEDIASERVICE']._serialized_start=277
  _globals['_MEDIASERVICE']._serialized_end=478
# @@protoc_insertion_point(module_scope)
