# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import media_pb2 as media__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in media_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MediaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TextToSpeech = channel.unary_unary(
                '/MediaService/TextToSpeech',
                request_serializer=media__pb2.TextRequest.SerializeToString,
                response_deserializer=media__pb2.SpeechResponse.FromString,
                _registered_method=True)
        self.SpeechToText = channel.unary_unary(
                '/MediaService/SpeechToText',
                request_serializer=media__pb2.SpeechRequest.SerializeToString,
                response_deserializer=media__pb2.TextResponse.FromString,
                _registered_method=True)
        self.FilteredTextToSpeech = channel.unary_unary(
                '/MediaService/FilteredTextToSpeech',
                request_serializer=media__pb2.TextRequest.SerializeToString,
                response_deserializer=media__pb2.SpeechResponse.FromString,
                _registered_method=True)
        self.FER = channel.unary_unary(
                '/MediaService/FER',
                request_serializer=media__pb2.ImageRequest.SerializeToString,
                response_deserializer=media__pb2.EmotionsArray.FromString,
                _registered_method=True)


class MediaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TextToSpeech(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpeechToText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FilteredTextToSpeech(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FER(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TextToSpeech': grpc.unary_unary_rpc_method_handler(
                    servicer.TextToSpeech,
                    request_deserializer=media__pb2.TextRequest.FromString,
                    response_serializer=media__pb2.SpeechResponse.SerializeToString,
            ),
            'SpeechToText': grpc.unary_unary_rpc_method_handler(
                    servicer.SpeechToText,
                    request_deserializer=media__pb2.SpeechRequest.FromString,
                    response_serializer=media__pb2.TextResponse.SerializeToString,
            ),
            'FilteredTextToSpeech': grpc.unary_unary_rpc_method_handler(
                    servicer.FilteredTextToSpeech,
                    request_deserializer=media__pb2.TextRequest.FromString,
                    response_serializer=media__pb2.SpeechResponse.SerializeToString,
            ),
            'FER': grpc.unary_unary_rpc_method_handler(
                    servicer.FER,
                    request_deserializer=media__pb2.ImageRequest.FromString,
                    response_serializer=media__pb2.EmotionsArray.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MediaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MediaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MediaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TextToSpeech(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MediaService/TextToSpeech',
            media__pb2.TextRequest.SerializeToString,
            media__pb2.SpeechResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SpeechToText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MediaService/SpeechToText',
            media__pb2.SpeechRequest.SerializeToString,
            media__pb2.TextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FilteredTextToSpeech(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MediaService/FilteredTextToSpeech',
            media__pb2.TextRequest.SerializeToString,
            media__pb2.SpeechResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FER(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MediaService/FER',
            media__pb2.ImageRequest.SerializeToString,
            media__pb2.EmotionsArray.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
