# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: speech.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'speech.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cspeech.proto\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"#\n\rSpeechRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\"\x1c\n\x0cTextResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"$\n\x0eSpeechResponse\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x32\xa4\x01\n\rSpeechService\x12-\n\x0cTextToSpeech\x12\x0c.TextRequest\x1a\x0f.SpeechResponse\x12-\n\x0cSpeechToText\x12\x0e.SpeechRequest\x1a\r.TextResponse\x12\x35\n\x14\x46ilteredTextToSpeech\x12\x0c.TextRequest\x1a\x0f.SpeechResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speech_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTREQUEST']._serialized_start=16
  _globals['_TEXTREQUEST']._serialized_end=43
  _globals['_SPEECHREQUEST']._serialized_start=45
  _globals['_SPEECHREQUEST']._serialized_end=80
  _globals['_TEXTRESPONSE']._serialized_start=82
  _globals['_TEXTRESPONSE']._serialized_end=110
  _globals['_SPEECHRESPONSE']._serialized_start=112
  _globals['_SPEECHRESPONSE']._serialized_end=148
  _globals['_SPEECHSERVICE']._serialized_start=151
  _globals['_SPEECHSERVICE']._serialized_end=315
# @@protoc_insertion_point(module_scope)
