# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fer.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tfer.proto\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\",\n\x07\x45motion\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\"+\n\rEmotionsArray\x12\x1a\n\x08\x65motions\x18\x01 \x03(\x0b\x32\x08.Emotion\",\n\x0bImagesArray\x12\x1d\n\x06images\x18\x01 \x03(\x0b\x32\r.ImageRequest21\n\nFerService\x12#\n\x03\x46\x45R\x12\x0c.ImagesArray\x1a\x0e.EmotionsArrayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=13
  _globals['_IMAGEREQUEST']._serialized_end=47
  _globals['_EMOTION']._serialized_start=49
  _globals['_EMOTION']._serialized_end=93
  _globals['_EMOTIONSARRAY']._serialized_start=95
  _globals['_EMOTIONSARRAY']._serialized_end=138
  _globals['_IMAGESARRAY']._serialized_start=140
  _globals['_IMAGESARRAY']._serialized_end=184
  _globals['_FERSERVICE']._serialized_start=186
  _globals['_FERSERVICE']._serialized_end=235
# @@protoc_insertion_point(module_scope)
